### ISSUE TITLE
item.twig

### ISSUE THREAD

**Issue by diomed** [jgonyea/grav-theme-editorial#8] opened 2018-03-26 13:14 UTC
RuntimeException (400)
Template "item.html.twig" is not defined.

**Comment by jgonyea** [comment] 2018-03-29 01:35
Hi, @diomed,
Where are you seeing that message? Thanks!

**Comment by diomed** [comment] 2018-03-29 09:55
I see it coz you're missing a template that some other themes have, and yours don't.
[For Example](https://github.com/tranduyhung/grav-theme-clean-blog/tree/master/templates)

**Comment by jgonyea** [comment] 2018-03-30 00:17
Sorry, I meant, what's calling the item twig file. I'll try to get it added soon.

**Comment by diomed** [comment] 2018-03-30 13:40
it's not an error per se, but when one comes from different theme that has that template, it is.

**Comment by jgonyea** [comment] 2018-03-30 18:47
Hmm, then I think the issue is more that you switched from a theme that uses that twig definition than it is editorial not having it.  Technically, a theme could implement 100 twig definitions, but I wouldn't expect editorial to support them.  You as the site owner would either need to copy them over or create your own.

Does that make sense, @diomed ?

**Comment by diomed** [comment] 2018-03-30 19:37
I've used several themes: fact remains that majority of themes available on list of themes on grav site HAS item.twig file.

**Comment by jgonyea** [comment] 2018-03-30 19:47
Ok, I'll look into it.  Thanks.

**Comment by jgonyea** [comment] 2022-03-07 04:36
Fixed in 1.0.0

**Closed by jgonyea** 2022-03-07 04:36 UTC
Labels: bug, need more information
